--- PhantomVim core: terminal-first mouseless IDE glue.
---
--- The bottom terminal is the controller. This module makes nvim, the left
--- explorer and the right AI panel "follow" what happens there:
---   * the shell writes its PWD to a small file at every prompt (cwd.txt)
---   * a poller in nvim picks that up, runs :chdir, and re-roots the explorer
---     + refreshes the AI panel title (so all 3 panes show the same location)
---   * `n foo.py` (and any `nvim foo.py` typed into the terminal) appends the
---     path to open.txt instead of spawning a nested editor; the poller opens
---     each path in the central editor window and reveals it in the explorer
---   * <A-h/j/k/l> and <F2/F3/F4> jump focus between the four zones in all
---     modes (mouseless), <F1> opens the keymap Guide (also the default
---     screen when no file is open; the LazyVim/`snacks` dashboard is off).

local M = {}

local DIR = vim.fn.stdpath("state") .. "/phantom"
local CWD_FILE = DIR .. "/cwd.txt"
local OPEN_FILE = DIR .. "/open.txt"
local LOCK_FILE = DIR .. "/poller.lock"
local RCFILE = DIR .. "/termrc"

local p5 = require("config.p5")

local shell = vim.env.SHELL or "bash"
local shell_name = vim.fn.fnamemodify(shell, ":t")

---@private
local function ensure_dir()
  vim.fn.mkdir(DIR, "p")
end

---@private
---Does this buffer belong to one of the fixed zones (terminal / explorer / AI)?
---@param buf number
local function zone_of_buffer(buf)
  local name = vim.api.nvim_buf_get_name(buf) or ""
  local ft = vim.bo[buf].filetype or ""
  if ft == "snacks_terminal" or name:match("^term://") then
    return name:match("opencode") and "ai" or "terminal"
  end
  if ft == "neo-tree" or name:match("neo%-tree") then
    return "explorer"
  end
  if name:match("opencode") then
    return "ai"
  end
  if ft == "phantomguide" or name:match("Phantom Guide") then
    return "guide"
  end
  return "editor"
end

---@private
---Windows of a given zone (1 or more), terminal/neo-tree/opencode may stack.
---@param zone string
local function zone_windows(zone)
  local wins = {}
  for _, win in ipairs(vim.api.nvim_list_wins()) do
    if zone_of_buffer(vim.api.nvim_win_get_buf(win)) == zone then
      wins[#wins + 1] = win
    end
  end
  return wins
end

---Focus (or open) one of the four zones.
---@param zone "explorer"|"terminal"|"ai"|"editor"
function M.zone_focus(zone)
  local wins = zone_windows(zone)
  if #wins == 0 and zone == "editor" then
    -- the Guide lives in the editor area, so it doubles as a focus target
    wins = zone_windows("guide")
  end
  if #wins > 0 then
    vim.api.nvim_set_current_win(wins[#wins])
    return
  end
  if zone == "editor" or zone == "guide" then
    -- no dedicated window: reuse the current one
    return
  end
  if zone == "explorer" then
    require("neo-tree.command").execute({ action = "show", source = "filesystem", position = "left" })
  elseif zone == "terminal" then
    M.terminal_toggle()
  elseif zone == "ai" then
    vim.cmd("silent OpenCodeToggle")
  end
end

---Toggle the terminal controller (bash + PhantomVim rc so every prompt syncs
---PWD and `n file` / `nvim file` opens in the editor instead of nesting).
function M.terminal_toggle()
  require("snacks").terminal.toggle(M.get_term_cmd(), {
    cwd = vim.uv.cwd() or vim.fn.getcwd(),
    env = {
      TERM = "xterm-256color",
      PHANTOM_STATE = DIR,
    },
    win = {
      position = "bottom",
      height = 0.28,
      relative = "editor",
      wo = { winbar = "%{%v:lua.require('config.phantom').winbar()%}" },
    },
  })
end

---Command vector used for PhantomVim's controller terminal (interactive bash
---with our rcfile; zsh falls back to plain interactive $SHELL - only bash gets
---the PWD-sync hooks injected, which keeps the shell's own config intact).
function M.get_term_cmd()
  if shell_name == "bash" then
    return { "bash", "--rcfile", RCFILE }
  end
  return { shell }
end

---@private
---Write the bash rcfile the controller terminal sources: user's own bashrc
---first, then the hook that mirrors PWD, and the `n` opener helper.
local function write_rc()
  local rc = table.concat({
    "# PhantomVim controller terminal (autogenerated)",
    "if [ -f \"$HOME/.bashrc\" ]; then . \"$HOME/.bashrc\"; fi",
    [[export PHANTOM_STATE="]] .. DIR .. [["]],
    "_pv_last_pwd=\"\"",
    "_pv_sync() {",
    "  local p=\"$PWD\"",
    "  if [ \"$p\" != \"$_pv_last_pwd\" ]; then",
    "    _pv_last_pwd=\"$p\"",
    '    printf \'%s\\n\' "$p" > "' .. CWD_FILE .. '"',
    "  fi",
    "}",
    'PROMPT_COMMAND="_pv_sync${PROMPT_COMMAND:+;$PROMPT_COMMAND}"',
    "",
    "# open paths in the editor above (never a nested editor inside the panel)",
    'n() { printf \'%s\\n\' "$@" > "' .. OPEN_FILE .. '"; }',
    "_pv_open() { n \"$@\"; }",
    "alias nvim=_pv_open",
    "alias vim=_pv_open",
    "alias vi=_pv_open",
    "alias openide=n",
  }, "\n") .. "\n"
  local f = io.open(RCFILE, "w")
  if f then
    f:write(rc)
    f:close()
  end
end

---@private
---Explorer re-roots to a new working directory without stealing focus.
---@param dir string
local function tree_re_root(dir)
  local ok, tree_cmd = pcall(require, "neo-tree.command")
  if not ok then
    return
  end
  pcall(tree_cmd.execute, {
    action = "show",
    source = "filesystem",
    dir = dir,
    position = "left",
    focus = false,
  })
end

---@private
---A window able to host a file: a real editor window, or the Guide's window
---(it lives in the editor area), or nil.
local function editor_window()
  local editors = zone_windows("editor")
  if #editors > 0 then
    return editors[#editors]
  end
  local guides = zone_windows("guide")
  if #guides > 0 then
    return guides[#guides]
  end
  return nil
end

---@private
---Open a path (file or directory) in the central editor window.
---@param path string
local function open_path_in_editor(path)
  path = vim.fn.expand(path)
  if path == "" then
    return
  end
  local stat = vim.uv.fs_stat(path)
  if not stat then
    require("snacks").notify.warn("Can't open: " .. path)
    return
  end
  local is_dir = stat.type == "directory"
  vim.schedule(function()
    -- NEVER :edit the terminal/explorer/AI panes: pick a safe editor window
    -- first, and only if there is none, split one above the bottom panes.
    local win = editor_window()
    if not win then
      local anchor = nil
      for _, z in ipairs({ "terminal", "ai", "explorer" }) do
        local ws = zone_windows(z)
        if #ws > 0 then
          anchor = ws[#ws]
          break
        end
      end
      if anchor and vim.api.nvim_win_is_valid(anchor) then
        local tmp = vim.api.nvim_create_buf(true, false)
        win = vim.api.nvim_open_win(tmp, true, { split = "above", win = anchor })
      else
        win = vim.api.nvim_get_current_win()
      end
    end
    if vim.api.nvim_win_is_valid(win) then
      vim.api.nvim_set_current_win(win)
    end
    if is_dir then
      vim.fn.chdir(path)
      tree_re_root(path)
    else
      vim.cmd("edit " .. vim.fn.fnameescape(path))
      pcall(function()
        require("neo-tree.command").execute({ action = "reveal", source = "filesystem" })
      end)
    end
  end)
end

---@private
---Consume pending "open this path" requests from the controller terminal.
local function consume_open_requests()
  local f, perr = io.open(OPEN_FILE, "r")
  if not f then
    return
  end
  local content = f:read("*a") or ""
  f:close()
  if content == "" then
    return
  end
  -- truncate first (idempotent even if an `edit` errors below)
  io.open(OPEN_FILE, "w"):close()
  for line in content:gmatch("[^\r\n]+") do
    local trimmed = line:gsub("^%s+", ""):gsub("%s+$", "")
    if trimmed ~= "" then
      open_path_in_editor(trimmed)
    end
  end
end

---@private
---The heart: keep all panes in sync with the controller terminal's PWD.
local function sync_cwd()
  local f = io.open(CWD_FILE, "r")
  if not f then
    return
  end
  local dir = (f:read("*a") or ""):gsub("%s+$", "")
  f:close()
  if dir == "" or dir == (vim.uv.cwd() or "") then
    return
  end
  if vim.uv.fs_stat(dir) and vim.uv.fs_stat(dir).type == "directory" then
    vim.fn.chdir(dir)
  end
end

---On :chdir: re-root explorer + let the AI panel title follow the location.
function M.on_directory_changed()
  local dir = vim.uv.cwd() or vim.fn.getcwd()
  tree_re_root(dir)
  vim.api.nvim_exec_autocmds("User", { pattern = "PhantomDirChanged", modeline = false })
end

-- Keep the left explorer in step with whatever `cd` the controller terminal
-- just issued (the poller's :chdir fires this event).
vim.api.nvim_create_autocmd("DirChanged", {
  callback = function()
    vim.schedule(M.on_directory_changed)
  end,
})

---@private
local timer

---One full sync pass (also called by the timer every second).
function M.tick()
  local ok, err = pcall(function()
    sync_cwd()
    consume_open_requests()
  end)
  if not ok then
    vim.notify("phantom sync error: " .. tostring(err), vim.log.levels.WARN)
  end
end

---@private
---Is any actual Phantom pane (terminal/explorer/AI) on screen?
local function pane_visible()
  for _, w in ipairs(vim.api.nvim_list_wins()) do
    local zone = zone_of_buffer(vim.api.nvim_win_get_buf(w))
    if zone == "terminal" or zone == "ai" or zone == "explorer" then
      return true
    end
  end
  return false
end

---@private
---Refuse the sync lock if a live *other* process owns it, so stray/headless
---nvim instances can never steal the poll from the real session.
---@return boolean
local function acquire_lock()
  local f = io.open(LOCK_FILE, "r")
  if f then
    local pid = tonumber((f:read("*a") or ""):match("%d+"))
    f:close()
    if pid and pid ~= vim.fn.getpid() then
      local alive = vim.uv.kill(pid, 0)
      if alive then
        return false
      end
    end
  end
  local w = io.open(LOCK_FILE, "w")
  if w then
    w:write(tostring(vim.fn.getpid()))
    w:close()
  end
  return true
end

---@private
local function release_lock()
  local f = io.open(LOCK_FILE, "r")
  if f then
    local pid = tonumber((f:read("*a") or ""):match("%d+"))
    f:close()
    if pid == vim.fn.getpid() then
      os.remove(LOCK_FILE)
    end
  end
end

vim.api.nvim_create_autocmd("VimLeavePre", { callback = release_lock })

---@private
---Start the foreground sync loop, but only once a Phantom pane exists and only
---if no other live process is already polling. Headless/stray nvim instances
---(experiments, `nvim --embed` agents, test harnesses) must never steal the
---poll from the real session, so a visible UI is required unless the test
---harness explicitly opts in with `vim.g.phantom_force_poller = true`.
local function ensure_poller()
  if timer then
    return
  end
  if not pane_visible() then
    return
  end
  if not vim.g.phantom_force_poller and #vim.api.nvim_list_uis() == 0 then
    return
  end
  if not acquire_lock() then
    return
  end
  timer = (vim.uv).new_timer()
  timer:start(500, 1000, vim.schedule_wrap(M.tick))
end

---Test hook: is this process currently running the foreground poller?
function M._poller_active()
  return timer ~= nil
end

---Start the sync machinery (also re-kicked when a Phantom pane appears).
local did_start = false
function M.start()
  if did_start then
    return
  end
  did_start = true
  ensure_dir()
  write_rc()
  ensure_poller()
end

-- A pane appearing later (or a win focus change) must start the poller even if
-- start() ran before any controller window existed (e.g. `nvim --embed` or a
-- bare headless load that never builds a Phantom IDE).
vim.api.nvim_create_autocmd({ "WinEnter", "BufEnter" }, {
  callback = function()
    vim.schedule(ensure_poller)
  end,
})

---Escape '%' so shell paths can't break winbar expansion.
---@param s string
local function esc(s)
  return (s or ""):gsub("%%", "%%%%")
end

---@private
---Winbar for every zone: terminal/explorer/AI get their fixed P5 titles (with
---the current location), the editor shows the open file's path and exit it.
function M.winbar()
  local win = vim.api.nvim_get_current_win()
  local buf = vim.api.nvim_win_get_buf(win)
  local zone = zone_of_buffer(buf)
  local home = os.getenv("HOME") or ""
  local dir = esc((vim.uv.cwd() or vim.fn.getcwd()):gsub("^" .. vim.pesc(home), "~"))
  if zone == "terminal" then
    return "%#P5TitleGold# TERMINAL %#P5TitleBar# CONTROLLER │ " .. dir .. "%#P5TitleBar# ▏ %*"
  elseif zone == "ai" then
    return "%#P5Title# OPENCODE %#P5TitleBar# │ " .. dir .. "%#P5TitleBar# ▏ %*"
  elseif zone == "explorer" then
    return "%#P5TitleBar# EXPLORER │ " .. dir .. "%#P5TitleBar# ▏ %*"
  elseif zone == "guide" then
    return "%#P5TitleRed# PHANTOM·VIM GUIDE %#P5TitleBar# │ KEYBINDS UNLOCKED %#P5TitleBar# ▏ %*"
  end
  local name = vim.api.nvim_buf_get_name(buf)
  if name == "" then
    return "%#P5Title# NO TARGET %#P5TitleBar# │ ,, or <F1> for the Guide %*"
  end
  local rel = esc(vim.fn.fnamemodify(name, ":~:."))
  return "%#P5Title# ◈ " .. rel .. " %#P5TitleBar# ▏ %*"
end

---@private
---Human description for a keymap row (used by the Guide's full dump).
local function key_desc(k)
  if k.desc and k.desc ~= "" then
    return k.desc
  end
  local rhs = k.rhs
  if not rhs or rhs == "" then
    return ""
  end
  if rhs:sub(1, 1) ~= "<" then
    return rhs
  end
  return ""
end

---@private
---Render the live keymap table (everything registered, nothing omitted).
local function keymap_dump()
  local modes = { { "n", "Normal" }, { "i", "Insert" }, { "v", "Visual" }, { "x", "Visual" }, { "o", "Operator" }, { "c", "Command" }, { "t", "Terminal" } }
  local rows = {}
  for _, mode in ipairs(modes) do
    local m = mode[1]
    for _, k in ipairs(vim.api.nvim_get_keymap(m)) do
      local lhs = k.lhs
      if lhs and lhs ~= "" and not lhs:match("<Plug>") and not lhs:match("<SNR>") and lhs ~= "<Nop>" then
        local desc = key_desc(k)
        if desc ~= "" and not desc:match("^function") then
          rows[#rows + 1] = { m, lhs, desc }
        end
      end
    end
  end
  table.sort(rows, function(a, b)
    if a[1] ~= b[1] then
      return a[1] < b[1]
    end
    return a[2] < b[2]
  end)
  return rows
end

---Build the Guide content (banner + curated sections + live full dump).
function M.guide_lines()
  local lines = {}
  local function h(text, hl)
    lines[#lines + 1] = { text = text, hl = hl }
  end
  local function kv(left, right)
    lines[#lines + 1] = { text = "  ▸ " .. left .. "   " .. right, hl = "P5BannerArrow" }
  end

  lines[#lines + 1] = { text = "▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓", hl = "P5BannerDim" }
  h("PHANTOM·THIEVES // CODING LEAP", "P5BannerTitle")
  h("GIMME YOUR CODE", "P5BannerGold")
  h("", nil)
  h("-- ZONES (focus any pane from anywhere, mouseless) --", "P5BannerDim")
  kv("<F1> / ,,", "Keymap Guide (this screen, anywhere, anytime)")
  kv("<A-1>/<F3>", "focus TERMINAL (controller)")
  kv("<A-2>", "focus EDITOR")
  kv("<A-3>/<F4>", "focus AI CHAT")
  kv("<A-h>/<F2>", "focus EXPLORER          <A-j/k/l>  also focus terminal/editor/AI")
  kv("<A-Up/Down/Left/Right>", "resize the focused window")
  h("", nil)
  h("-- TERMINAL-FIRST CONTROLLER --", "P5BannerDim")
  kv("n <path>", "open file/dir in the editor above")
  kv("nvim <path>", "also opens here (never nests a second editor)")
  kv("cur dir", "the left explorer + AI title follow the terminal's PWD")
  kv("gf", "open file under cursor in the editor")
  h("", nil)
  h("-- PHANTOM COMMANDS (leader is `,`) --", "P5BannerDim")
  kv(",oa", "AI chat panel (toggle)   ,oq ask with buffer context")
  kv(",os", "select an AI action      go/goo send range/line")
  kv(",ot", "terminal (toggle)        ,ol  reassemble the layout")
  kv(",e", "reveal file in explorer   (,E  toggle explorer)")
  h("", nil)
  h("-- NVIM ESSENTIALS --", "P5BannerDim")
  kv("w e b", "move word-wise        i a o I  enter insert")
  kv("dd yy p", "delete / yank / paste     x r  delete/replace char")
  kv("u  <C-r>", "undo / redo              .  repeat last change")
  kv("/ ? n N", "search fwd/bwd + next/prev    *  word under cursor")
  kv("%", "jump to match          gg / G  top / bottom")
  kv("H M L", "screen top/mid/bottom      <C-d>/<C-u> half page down/up")
  kv("v V", "char / line visual    o  other end of selection")
  kv("<C-w>w", "next window          <C-w>h/j/k/l  focus a window")
  kv("<C-i>/<C-o>", "jump list forward/back  gt/gT  next/prev tab")
  kv(":e <file>", "open file            :w  save        :q  quit")
  kv("<C-\\><C-n>", "exit terminal to normal mode")
  h("", nil)
  h("-- LAZYVIM GROUPS (press `,` then pause for the live menu) --", "P5BannerDim")
  kv(",f", "find: files/recent/buffers/word   ,g  git: status/log/lazygit")
  kv(",s", "search: symbols/todo/floating     ,x  diagnostics/quickfix")
  kv(",w", "window: splits/create/zoom        ,b  buffers: delete/sort")
  kv(",c", "code: LSP actions/rename/format   \",l\"  LSP: info/diagnostics")
  kv(",q", "quit/session shell                ,h  help/tabs/windows")
  h("", nil)
  h("-- FULL LIVE KEYMAP DUMP (all modes, nothing omitted) --", "P5BannerDim")
  local rows = keymap_dump()
  lines[#lines + 1] = { text = "  (modes: n normal · i insert · v visual · o operator · c command · t terminal)", hl = "P5BannerDim" }
  for _, row in ipairs(rows) do
    lines[#lines + 1] = {
      text = string.format("  %s  %-16s  %s", row[1], row[2], row[3]),
      hl = "None",
    }
  end
  h("▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓", "P5BannerDim")
  return lines
end

---Show the PhantomVim Guide (default screen + <F1>/`,,`).
function M.show_guide()
  -- already on screen somewhere? re-render it and focus the window, never
  -- spawn a second guide window next to the first one.
  for _, w in ipairs(vim.api.nvim_list_wins()) do
    local b = vim.api.nvim_win_get_buf(w)
    if vim.api.nvim_buf_is_valid(b) and vim.api.nvim_buf_is_loaded(b) and vim.bo[b].filetype == "phantomguide" then
      local existing = b
      vim.bo[existing].modifiable = true
      local lines = M.guide_lines()
      local texts = vim.iter(lines):map(function(l) return l.text end):totable()
      vim.api.nvim_buf_set_lines(existing, 0, -1, false, texts)
      vim.api.nvim_buf_clear_namespace(existing, -1, 0, -1)
      vim.api.nvim_set_hl(0, "PhantomGuideBg", { link = "Normal" })
      vim.api.nvim_buf_add_highlight(existing, -1, "PhantomGuideBg", 0, 0, -1)
      for i, l in ipairs(lines) do
        if type(l.hl) == "string" and l.hl ~= "None" then
          vim.api.nvim_buf_add_highlight(existing, -1, l.hl, i - 1, 0, -1)
        end
      end
      vim.bo[existing].modifiable = false
      vim.api.nvim_set_current_win(w)
      return
    end
  end

  local target_buf = nil
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if vim.bo[buf].filetype == "phantomguide" and vim.api.nvim_buf_is_loaded(buf) then
      target_buf = buf
      break
    end
  end
  target_buf = target_buf or vim.api.nvim_create_buf(true, false)
  -- the Guide must never look/act like an on-disk file: no swap file, no
  -- recovery prompt, and it gets wiped (not hidden) so it can't linger.
  pcall(vim.api.nvim_buf_set_name, target_buf, "")
  vim.bo[target_buf].buftype = "nofile"
  vim.bo[target_buf].swapfile = false
  vim.bo[target_buf].filetype = "phantomguide"
  vim.bo[target_buf].bufhidden = "wipe"
  vim.bo[target_buf].modifiable = true
  local lines = M.guide_lines()
  local texts = vim.iter(lines):map(function(l) return l.text end):totable()
  vim.api.nvim_buf_set_lines(target_buf, 0, -1, false, texts)
  vim.api.nvim_buf_clear_namespace(target_buf, -1, 0, -1)
  vim.api.nvim_set_hl(0, "PhantomGuideBg", { link = "Normal" })
  vim.api.nvim_buf_add_highlight(target_buf, -1, "PhantomGuideBg", 0, 0, -1)
  for i, l in ipairs(lines) do
    if type(l.hl) == "string" and l.hl ~= "None" then
      vim.api.nvim_buf_add_highlight(target_buf, -1, l.hl, i - 1, 0, -1)
    end
  end
  vim.bo[target_buf].modifiable = false

  vim.api.nvim_buf_set_keymap(target_buf, "n", "q", "<cmd>hide<CR>", { noremap = true, silent = true, desc = "Close guide" })
  vim.api.nvim_buf_set_keymap(target_buf, "n", "<Esc>", "<cmd>hide<CR>", { noremap = true, silent = true, desc = "Close guide" })
  vim.api.nvim_buf_set_keymap(target_buf, "n", "<C-o>", "<cmd>hide<CR>", { noremap = true, silent = true, desc = "Close guide" })

  local wins = zone_windows("editor")
  local win = nil
  if #wins > 0 then
    win = wins[1]
  else
    -- no plain editor window: split one above the last fixed-zone window so the
    -- terminal/explorer/AI panes are never hijacked by the Guide
    local zones = { "terminal", "explorer", "ai" }
    local anchor = nil
    for _, z in ipairs(zones) do
      local ws = zone_windows(z)
      if #ws > 0 then
        anchor = ws[#ws]
        break
      end
    end
    if anchor and vim.api.nvim_win_is_valid(anchor) then
      win = vim.api.nvim_open_win(target_buf, true, { split = "above", win = anchor })
    else
      win = vim.api.nvim_get_current_win()
    end
  end
  if vim.api.nvim_win_is_valid(win) then
    vim.api.nvim_win_set_buf(win, target_buf)
    vim.api.nvim_set_current_win(win)
  end
end

---Bring the Guide back whenever all real content buffers have been closed.
---The event buffer param is used to keep the fixed panes out of the loop:
---opening/focusing a terminal, explorer or AI pane must never re-spawn the
---Guide (that produced stacks of guide windows before).
---@param ev? table Autocmd event (has `.match` = buffer number)
function M.maybe_show_guide_on_empty(ev)
  -- never pile up: if any window already shows the Guide, leave it alone
  for _, w in ipairs(vim.api.nvim_list_wins()) do
    local b = vim.api.nvim_win_get_buf(w)
    if vim.api.nvim_buf_is_valid(b) and vim.api.nvim_buf_is_loaded(b) and vim.bo[b].filetype == "phantomguide" then
      return
    end
  end
  if ev and type(ev.buf) == "number" and ev.buf ~= 0 and vim.api.nvim_buf_is_valid(ev.buf) then
    local zone = zone_of_buffer(ev.buf)
    if zone ~= "editor" and zone ~= "guide" then
      return
    end
  end
  local has_real = false
  for _, buf in ipairs(vim.api.nvim_list_bufs()) do
    if vim.api.nvim_buf_is_valid(buf) and vim.api.nvim_buf_is_loaded(buf) then
      local name = vim.api.nvim_buf_get_name(buf)
      local ft = vim.bo[buf].filetype or ""
      if vim.bo[buf].buftype == "" and name ~= "" and ft ~= "phantomguide" then
        has_real = true
        break
      end
    end
  end
  if not has_real and zone_of_buffer(vim.api.nvim_get_current_buf()) ~= "guide" then
    M.show_guide()
  end
end

---Configure the global keymaps once (zone focus + guide + F-key layer).
function M.setup_keymaps()
  -- LazyVim uses <A-h/j/k/l> for window resize; move resize to the arrow keys
  -- so Alt+directional can be our zone focus layer.
  vim.keymap.set("n", "<A-Left>", function() vim.api.nvim_win_set_width(0, vim.api.nvim_win_get_width(0) + 2) end, { desc = "Resize wider" })
  vim.keymap.set("n", "<A-Right>", function() vim.api.nvim_win_set_width(0, vim.api.nvim_win_get_width(0) - 2) end, { desc = "Resize narrower" })
  vim.keymap.set("n", "<A-Up>", function() vim.api.nvim_win_set_height(0, vim.api.nvim_win_get_height(0) + 2) end, { desc = "Resize taller" })
  vim.keymap.set("n", "<A-Down>", function() vim.api.nvim_win_set_height(0, vim.api.nvim_win_get_height(0) - 2) end, { desc = "Resize shorter" })

  local zones = { h = "explorer", j = "terminal", k = "editor", l = "ai" }
  for key, zone in pairs(zones) do
    vim.keymap.set("n", "<A-" .. key .. ">", function() M.zone_focus(zone) end, { desc = "Focus " .. zone })
    vim.keymap.set("t", "<A-" .. key .. ">", "<C-\\><C-n><cmd>lua require('config.phantom').zone_focus('" .. zone .. "')<CR>", { desc = "Focus " .. zone })
  end
  -- one-hand digit layer (mirrors <F1>/<F2>/<F3>/<F4>): A-1 terminal, A-2
  -- editor, A-3 AI; the explorer keeps <A-h>/<F2>. Works from any mode.
  local digits = { ["1"] = "terminal", ["2"] = "editor", ["3"] = "ai" }
  for key, zone in pairs(digits) do
    vim.keymap.set("n", "<A-" .. key .. ">", function() M.zone_focus(zone) end, { desc = "Focus " .. zone })
    vim.keymap.set("t", "<A-" .. key .. ">", "<C-\\><C-n><cmd>lua require('config.phantom').zone_focus('" .. zone .. "')<CR>", { desc = "Focus " .. zone })
  end
  vim.keymap.set("n", "<F1>", M.show_guide, { desc = "Open the PhantomVim Guide" })
  vim.keymap.set("t", "<F1>", "<C-\\><C-n><cmd>lua require('config.phantom').show_guide()<CR>", { desc = "Open the PhantomVim Guide" })
  vim.keymap.set("n", "<leader><leader>", M.show_guide, { desc = "PhantomVim Guide" })
  vim.keymap.set("n", "<F2>", function() M.zone_focus("explorer") end, { desc = "Explorer" })
  vim.keymap.set("n", "<F3>", function() M.zone_focus("terminal") end, { desc = "Terminal" })
  vim.keymap.set("n", "<F4>", function() M.zone_focus("ai") end, { desc = "OpenCode" })
  vim.keymap.set("t", "<F2>", "<C-\\><C-n><cmd>lua require('config.phantom').zone_focus('explorer')<CR>", { desc = "Explorer" })
  vim.keymap.set("t", "<F3>", "<C-\\><C-n><cmd>lua require('config.phantom').zone_focus('terminal')<CR>", { desc = "Terminal" })
  vim.keymap.set("t", "<F4>", "<C-\\><C-n><cmd>lua require('config.phantom').zone_focus('ai')<CR>", { desc = "OpenCode" })
end

return M